### ISSUE TITLE
Missing raylib.dll

### ISSUE THREAD

**Issue by daichungus** [SomeUnusualGames/Flag-Wars#2]
Upon opening the `FlagWars.exe` file found in the Windows version of this game, the game states that `raylib.dll` is missing. Perhaps it could be included with the .zip file?

![image](https://github.com/user-attachments/assets/423a1326-e7d6-44ea-bdff-3d58cacf7905)

**Comment by SomeUnusualGames** [comment]
Thanks for reporting!

The dll for raylib v5.0 has been added to the [itch.io release](https://someunusualgames.itch.io/flag-wars-argentina-vs-uruguay). I also updated the version from an old version (4.2).

Let me know if there's any issues :)

**Comment by daichungus** [comment]
Game opens right out the box now, thanks for fixing it!
